flaskblog/events/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length
from wtforms.fields.html5 import DateTimeField, DateField, TimeField


class EventForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=40)])
    startdate = DateField('Start', format='%Y-%m-%d', validators=[DataRequired()])
    starttime = TimeField('', format='%H:%M')
    enddate = DateField('End', format='%Y-%m-%d', validators=[DataRequired()])
    endtime = TimeField('', format='%H:%M')
    address = StringField('Address', validators=[Length(min=0, max=50)])
    note_event = TextAreaField('Note for the event', validators=[Length(min=0, max=200)])
    max_workers_needed = IntegerField('Number of workers needed', validators=[DataRequired()])
    submit = SubmitField('Post')

class TimeSheetForm(FlaskForm):
    clock_in = DateTimeField('Clock In')
    clock_out = DateTimeField('Clock Out')
    review = IntegerField('Review')

flaskblog/events/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Event, Worker_Event
from flaskblog.events.forms import EventForm, TimeSheetForm
from flaskblog.decorator import organizer, worker
from flaskblog.tasks import send_sms
from datetime import datetime

events = Blueprint('events', __name__)


@events.route("/event/new", methods=['GET', 'POST'])
@login_required
@organizer
def new_event():
    form = EventForm()
    if form.validate_on_submit():
        event = Event(title=form.title.data, startdatetime=datetime.combine(form.startdate.data, form.starttime.data),
                      enddatetime=datetime.combine(form.enddate.data, form.endtime.data),
                      address=form.address.data, note_event=form.note_event.data,
                      max_workers_needed=form.max_workers_needed.data, organizer_id=current_user.organizer.id)
        db.session.add(event)
        db.session.commit()
        flash('Your event has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_event.html', title='New Event',
                           form=form, legend='New Event')


@events.route("/event/<int:event_id>")
def event(event_id):
    event = Event.query.get_or_404(event_id)
    return render_template('event.html', title=event.title, event=event)


@events.route("/event/<int:event_id>/update", methods=['GET', 'POST'])
@login_required
@organizer
def update_event(event_id):
    event = Event.query.get_or_404(event_id)
    if event.organizer.user != current_user:
        abort(403)
    form = EventForm()
    if form.validate_on_submit():
        event.title = form.title.data
        event.startdatetime = datetime.combine(form.startdate.data, form.starttime.data)
        event.enddatetime = datetime.combine(form.enddate.data, form.endtime.data)
        event.address = form.address.data
        event.note_event = form.note_event.data
        event.max_workers_needed = form.max_workers_needed.data
        db.session.commit()

        attendees = event.get_accepted_workers + event.get_need_cover_workers + event.get_interested_workers
        print(attendees)
        phone_number_list = [attendee.phone for attendee in attendees]
        message = f"The event '{event.title}' on the {event.startdatetime} has been updated. Please check the details for any changes."
        for phone_number in phone_number_list:
            send_sms.delay(phone_number, message)

        flash('Your event has been updated!', 'success')
        return redirect(url_for('events.event', event_id=event.id))
    elif request.method == 'GET':
        form.title.data = event.title
        form.startdate.data = event.startdatetime.date()
        form.starttime.data = event.startdatetime.time()
        form.enddate.data = event.enddatetime.date()
        form.endtime.data = event.enddatetime.time()
        form.address.data = event.address
        form.note_event.data = event.note_event
        form.max_workers_needed.data = event.max_workers_needed
    return render_template('create_event.html', title='Update Event',
                           form=form, legend='Update Event')


@events.route("/event/<int:event_id>/delete", methods=['POST'])
@login_required
@organizer
def delete_event(event_id):
    event = Event.query.get_or_404(event_id)
    if event.organizer.user != current_user:
        abort(403)
    db.session.delete(event)
    db.session.commit()
    flash('Your event has been deleted!', 'success')
    return redirect(url_for('main.home'))


@events.route("/event/<int:event_id>/accept_event", methods=['POST'])
@login_required
def accept_event(event_id):
    event = Event.query.get_or_404(event_id)
    # not sure
    # if current_user.worker in event.get_accepted_workers:
    #     abort(403)
    new_worker_event = Worker_Event(event_id=event.id, state='accept', worker=current_user.worker)
    db.session.add(new_worker_event)
    db.session.commit()
    flash('You have been enrolled to this Event!', 'success')
    return redirect(url_for('events.event', event_id=event.id))


@events.route("/event/<int:event_id>/ask_cover_event", methods=['POST'])
# @login_required
def ask_cover_event(event_id):
    event = Event.query.get_or_404(event_id)
    # not sure
    # if current_user.worker in event.get_accepted_workers:
    #     abort(403)
    Worker_Event.query.filter_by(event_id=event.id, worker=current_user.worker).update({'state': 'request cover'})
    db.session.commit()
    flash('You have ask for cover for this Event!', 'success')
    return redirect(url_for('events.event', event_id=event.id))


@events.route("/event/<int:event_id>/cancel_cover_event", methods=['POST'])
@login_required
def cancel_cover_event(event_id):
    event = Event.query.get_or_404(event_id)
    # not sure
    # if current_user.worker in event.get_accepted_workers:
    #     abort(403)
    Worker_Event.query.filter_by(event_id=event.id, worker=current_user.worker).update({'state': 'accept'})
    db.session.commit()
    flash('You have cancelled you request for cover for this Event!', 'success')
    return redirect(url_for('events.event', event_id=event.id))


@events.route("/event/<int:event_id>/update_interest_status", methods=['POST'])
@login_required
def update_interest_status(event_id):
    event = Event.query.get_or_404(event_id)
    interest_status = request.form['interest_status']
    if interest_status == 'add':
        worker_event = Worker_Event(worker_id=current_user.worker.id, event_id=event.id, state='interested')
        db.session.add(worker_event)
    elif interest_status == 'remove':
        worker_event = Worker_Event.query.filter_by(worker_id=current_user.worker.id, event_id=event.id).first()
        db.session.delete(worker_event)
    db.session.commit()
    return redirect(url_for('events.event', event_id=event.id))


@events.route("/calendar")
@login_required
def calendar():
    if current_user.role == 'organizer':
        events = Event.query.order_by(Event.date_posted.asc()).filter_by(
            organizer=current_user.organizer).all()
        return render_template('calendar-organizer.html', events=events)
    elif current_user.role == 'worker':
        worker_events = Worker_Event.query.filter_by(worker=current_user.worker).all()
        return render_template('calendar-worker.html', worker_events=worker_events)


@events.route("/timesheet")
@login_required
def timesheet():
    page = request.args.get('page', 1, type=int)
    if current_user.role == 'organizer':
        events = Event.query.order_by(Event.date_posted.asc()).filter(Event.organizer == current_user.organizer,
                                                                      Event.startdatetime < datetime.now()).paginate(
            page=page, per_page=5)
        return render_template('timesheet-organizer.html', events=events)
    elif current_user.role == 'worker':
        worker_events = Worker_Event.query.filter(Worker_Event.worker == current_user.worker).paginate(page=page,
                                                                                                       per_page=5)
        print(worker_events)
        events = Worker_Event.query.group_by(Worker_Event.event_id).filter_by(worker=current_user.worker).all()

        return render_template('timesheet-worker.html', worker_events=worker_events)


@events.route('/event/<int:event_id>/time-sheet', methods=['GET', 'POST'])
def event_time_sheet(event_id):
    events = Event.query.all()
    for event in events:
        print(event)
        print(event.review_submitted)
    event = Event.query.get_or_404(event_id)
    worker_events = event.worker_event
    forms = []
    if request.method == 'POST':
        print(request.form)
        for worker_event in worker_events:
            worker_event.clock_in_organizer = datetime.strptime(request.form[f'clock_in_{worker_event.worker.id}'],
                                                                "%Y-%m-%dT%H:%M")
            worker_event.clock_out_organizer = datetime.strptime(request.form[f'clock_out_{worker_event.worker.id}'],
                                                                 "%Y-%m-%dT%H:%M")
            worker_event.review = request.form[f'review_{worker_event.worker.id}']
            db.session.commit()
        flash('Time-sheet successfully submitted', 'success')
        # return redirect(url_for('event_timesheet', event_id=event.id))
        return render_template('event_timesheet.html', event=event, worker_events=worker_events)
    else:
        for worker_event in worker_events:
            form = TimeSheetForm()
            forms.append((form, worker_event))
    return render_template('event_timesheet.html', event=event, worker_events=worker_events,
                           forms=forms)



#filter all the events where the timesheet has not been submitted
#    events = Event.query.filter(
#         Event.startdatetime < datetime.now(),
#         Event.organizer_id == current_user.organizer.id,
#         Worker_Event.event_id == Event.id,
#         Worker_Event.review == None).all()

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account-organizer.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.company_name.label(class="form-control-label") }}
                    {% if form.company_name.errors %}
                        {{ form.company_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.company_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.company_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.surname.label(class="form-control-label") }}
                    {% if form.surname.errors %}
                        {{ form.surname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.surname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.surname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.phone.label(class="form-control-label") }}
                    {% if form.phone.errors %}
                        {{ form.phone(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.phone.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.phone(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.address.label(class="form-control-label") }}
                    {% if form.address.errors %}
                        {{ form.address(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.address(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.note.label(class="form-control-label") }}
                    {% if form.note.errors %}
                        {{ form.note(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.note.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.note(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}

                <button href="{{ url_for('users.black_list', page=1) }}" className="btn btn-outline-info" type="button">
                    Update your
                    Team List of worker
                </button>
            </div>
        </form>
    </div>

{% endblock content %}

flaskblog/templates/calendar-worker.html
{% extends "layout.html" %}
{% block content %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                firstDay: 1,
                headerToolbar: {right: 'prev,next'},
                initialView: 'dayGridMonth',
                allDaySlot: false,
                footerToolbar: {center: 'listMonth,timeGridWeek,dayGridMonth'},
                views: {timeGridWeek: {dayHeaderFormat: {weekday: 'short'}}},
                aspectRatio: 1,
                titleFormat: {year: '2-digit', month: 'short', day: '2-digit'},
                dateClick: function (info) {
                    if (calendar.view = 'dayGridMonth') {
                        calendar.changeView('timeGridWeek', info.dateStr);
                    } else {
                        calendar.changeView('dayGridMonth', info.dateStr);
                    }
                },
                events: [
                    {% for worker_event in worker_events %}
                        {
                            title: '{{worker_event.event.title }}',
                            start: '{{worker_event.event.startdatetime.strftime("%Y-%m-%dT%H:%M:%S")}}',
                            end: '{{worker_event.event.enddatetime.strftime("%Y-%m-%dT%H:%M:%S")}}',
                            {% if worker_event.state == 'request cover' %}
                                color: 'blue',
                            {% elif worker_event.state == 'accept' %}
                                color: 'green',
                            {% else %}
                                color: 'red',
                            {% endif %}
                            url: 'event/{{worker_event.event.id}}'
                        },
                    {% endfor %}
                ],
                eventContent: function (info) {
                    return {html: info.event.title};
                },
                eventDisplay: 'block'
            });
            calendar.render();
        });
    </script>
    <div class="calendar-presentation">
        <h2><a class="article-title">Calendar</a></h2>
        <div id='calendar'></div>


    </div>

{% endblock content %}

flaskblog/templates/event_timesheet.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='profile_pics/' + event.organizer.picture) }}">
        <div class="media-body">
            <div class="article-metadata">
                <div class="row">
                    <div class="col-6"><a class="mr-2"
                                          href="{{ url_for('users.user_events', username=event.organizer.company_name) }}">{{ event.organizer.company_name }}</a>
                    </div>
                    <div class="col-6"><span class="float-right"><small
                            class="text-muted ">posted on : {{ event.date_posted.strftime('%Y-%m-%d') }}</small></span>
                    </div>
                </div>
            </div>
            <h2 class="article-title">{{ event.title }}</h2>
            <p class="article-content"><i aria-hidden="true" class="fa fa-map-marker"></i> {{ event.address }}</p>
            <p><i aria-hidden="true" class="fa fa-calendar"></i> {{ event.text_start_end_datetime }}</p>
            {% if event.note_event != "" %}
                <p><i aria-hidden="true" class="fa fa-pencil-square-o"></i>
                    {{ event.note_event }}</p>
            {% endif %}
            <p><i aria-hidden="true" class="fa fa-users"></i> {{ event.get_accepted_workers|length }} /
                {{ event.max_workers_needed }}{% if event.get_need_cover_workers|length != 0 %} ,
                    {{ event.get_need_cover_workers|length }} looking for cover{% endif %}
                {% if event.interested_workers|length != 0 %}
                    , {{ event.interested_workers|length }} interested{% endif %}</p>
            {% if worker_events|length != 0 %}
                <form action="{{ url_for('events.event_time_sheet', event_id=event.id) }}" method="post">
                    <div class="accordion" id="workereventAccordion">
                        {% for worker_event in worker_events %}
                            <div class="card">
                                <div class="card-header" id="HeadingWorkerAccepted{{ loop.index }}">
                                    <div class="mb-0">
                                        <div class="row">
                                            <div class="col-10">
                                                <button aria-controls="workereventcollapse{{ loop.index }}"
                                                        aria-expanded="true"
                                                        class="btn btn-link btn-block text-left"
                                                        data-target="#workereventcollapse{{ loop.index }}"
                                                        data-toggle="collapse"
                                                        type="button">
                                                <span><i aria-hidden="true"
                                                         class="fa fa-user"></i> {{ worker_event.worker.name }}
                                                </span>
                                                </button>
                                                <label for="clock_in_{{ worker_event.worker.id }}">Clock In:</label>
                                                <input type="datetime-local"
                                                       name="clock_in_{{ worker_event.worker.id }}"
                                                       value="{{ worker_event.event.startdatetime if worker_event.clock_in_organizer == None else worker_event.clock_in_organizer }}"
                                                       required>
                                                <br>
                                                <label for="clock_out_{{ worker_event.worker.id }}">Clock Out:</label>
                                                <input type="datetime-local"
                                                       name="clock_out_{{ worker_event.worker.id }}"
                                                       value="{{ worker_event.event.enddatetime if worker_event.clock_out_organizer == None else worker_event.clock_out_organizer }}"
                                                       required>
                                                <br>
                                                <label for="review_{{ worker_event.worker.id }}">Review:</label>
                                                <input type="range" class="form-range" id="slider"
                                                       name="review_{{ worker_event.worker.id }}"
                                                       value="{{ 5  if worker_event.review == None else worker_event.review }}"
                                                       min="0" max="5"
                                                       required>
                                                <span class="range-value"> {{ 5 if worker_event.review == None else worker_event.review }}
                                                </span> <i class="fas fa-star"></i>
                                            </div>
                                            <div class="col text-right">
                                                <button aria-controls="workereventcollapse{{ loop.index }}"
                                                        aria-expanded="true"
                                                        class="btn btn-link btn-block text-right"
                                                        data-target="#workereventcollapse{{ loop.index }}"
                                                        data-toggle="collapse"
                                                        type="button">
                                                    <i aria-hidden="true" class="fa fa-chevron-down"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div aria-labelledby="HeadingWorkerAccepted{{ loop.index }}" class="collapse"
                                     data-parent="#workereventAccordion"
                                     id="workereventcollapse{{ loop.index }}">
                                    <div class="card-body">
                                        <div class="container">
                                            <div class="row mt-4">
                                                <div class="col-5">
                                                    <img class="rounded-circle account-img"
                                                         src="{{ url_for('static', filename='profile_pics/' + worker_event.worker.picture) }}">
                                                </div>
                                                <div class="col-7">
                                                    <h5>{{ worker_event.worker.name }}</h5>
                                                    <h5>{{ worker_event.worker.age }} y</h5>
                                                    {% if worker_event.event.organizer.user ==
                                    current_user %}{{ worker_event.worker.get_star_html | safe }}{% endif %}
                                                    <h5>{{ worker_event.worker.note }}</h5>
                                                    <!-- Add other worker information here -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div>
                        <input type="submit" value="Submit Timesheet" class="btn btn-primary">

                    </div>
                </form>
            {% endif %}
            <br>
            {{ event.get_google_map_iframe | safe }}
        </div>
    </article>
    <script>
        window.onload = function () {
            let rangeInputs = document.querySelectorAll('.form-range');
            let rangeValues = document.querySelectorAll('.range-value');
            for (let i = 0; i < rangeInputs.length; i++) {
                rangeInputs[i].addEventListener('input', function () {
                    rangeValues[i].textContent = this.value;
                });
            }
        };
    </script>
{% endblock content %}

flaskblog/templates/home2.html
{% extends "layout2.html" %}

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}